---
mesos_agent_configurations:
  hostname: "{{ mesos_agent_hostname }}"
  ip: "{{ mesos_agent_ip }}"
  containerizers: "{{ mesos_agent_containerizers }}"
  launcher: "{{ mesos_agent_launcher }}"
  resources: "{{ mesos_agent_resources }}"
