---
mesos_ip: "{{ ansible_host }}"
mesos_hostname: "{{ inventory_hostname }}"

mesos_master_config_path: /etc/mesos-master
mesos_master_override_path: /etc/init/mesos-master.override
mesos_master_configurations: {}
mesos_master_default_configurations:
    quorum: "{{ (groups['mesos-master']|length /2)|round|int }}"

mesos_agent_config_path: /etc/mesos-slave
mesos_agent_override_path: /etc/init/mesos-slave.override
mesos_agent_configurations: {}
mesos_agent_default_configurations:
    containerizers: docker,mesos
    
#mesos_zk_path: /etc/mesos/zk
mesos_zk_override_path: /etc/init/zookeeper.override

#mesos_zk_myid_path: /etc/zookeeper/conf/myid
#mesos_zk_config_path: /etc/zookeeper/conf/zoo.cfg


mesos_install: false
mesos_install_from_repository: false
mesos_install_from_deb: true
mesos_configure: false
mesos_start: false
mesos_stop: false

# Marathon
mesos_marathon_api_url: ""
