---
- name: install prerequisites packages
  apt: name="{{ item }}"
  with_items: "{{ mesos_docker_required_apt_packages }}"

- name: add apt key for docker repsotiory
  apt_key:
    keyserver: "{{ mesos_docker_apt_key_server }}"
    id: "{{ mesos_docker_apt_id }}"
  

- name: add docker repository
  apt_repository:
    repo: "{{ mesos_docker_deb_repo }}"
    update_cache: yes
  
- name: install docker-engine
  apt: name=docker-engine

- name: start docker daemon
  service:
    name: docker
    state: started

- name: set mesos-agent containerizer docker support
  shell: echo "docker,mesos" > /etc/mesos-slave/containerizers
