---
- name: download spark archive
  delegate_to: "{{ spark_installer }}"
  get_url:
    url: "{{ spark_archive_url }}"
    dest: "{{ spark_archive_path }}"
  run_once: true

- name: check spark archive root path
  delegate_to: "{{ spark_installer }}"
  local_action: shell tar ztf {{ spark_archive_path }} | head -1 | xargs basename
  register: sparkarchiveroot
  run_once: true

- name: check spark installation directory
  set_fact: spark_install_dir="{{ spark_install_root_dir }}/{{ sparkarchiveroot.stdout }}"

- name: unarchive spark distribution
  unarchive:
    src: "{{ spark_archive_path }}"
    dest: "{{ spark_install_root_dir }}"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
    creates: "{{ spark_install_dir }}/conf/spark-env.sh"

- name: make symbolic link to spark installation directory
  file:
    src: "{{ spark_install_dir }}"
    dest: "{{ spark_home_dir }}"
    force: yes
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
    state: link

- name: add SPARK_HOME environment variable
  template:
    src: spark-home-env.j2
    dest: /etc/profile.d/Z99-spark-home.sh
