--
- name: mesos master settings
  copy:
    content: "{{ item.value }}"
    dest: "{{ mesos_master_config_path }}/{{ item.key }}"
  with_dict: "{{ mesos_master_default_configurations | combine(mesos_master_configurations) }}"

- name: clean mesos master settings
  shell: find {{ mesos_master_configurations }} -type f -empty -delete
  changed_when: false
