---
- name: add java repository
  apt_repository: repo="{{ java_repository_ppa }}"
  register: javarepoadded
  become: true

- name: update apt repository
  apt: update_cache=yes
  when: javarepoadded.changed
  become: true

- name: accept oracle license
  debconf: name='{{ java_oracle_installer }}' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: true

- name: install {{ java_oracle_installer }}
  apt: name="{{ java_oracle_installer }}" 
  become: true
